<?php

namespace Splicewire\Beam\Docs\Search;

use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Http\Request;
use Splicewire\Beam\Brand\BrandData;
use Splicewire\Beam\Docs\Chrome\DocsChrome;
use Splicewire\Beam\Docs\Data\DocsSearchFallbackData;
use Splicewire\Beam\Docs\Data\DocsSearchInputData;
use Splicewire\Beam\Docs\Data\DocsSearchResultData;
use Splicewire\Beam\Docs\Data\DocsSearchResultsData;
use Splicewire\Beam\Particle\Attributes\ParticleOp;
use Splicewire\Beam\Particle\OperationKind;
use Splicewire\Beam\Particle\Subject\NoSubject;
use Splicewire\Beam\Routing\HttpMethod;
use Splicewire\Beam\Ux\Access\EntryAccessResolver;
use Splicewire\Beam\Ux\Containment\UrlResolver;
use Splicewire\Beam\Ux\Http\PublicEntryGate;
use Splicewire\Beam\Ux\Models\BeamUxEntry;

/**
 * `docs.search(q)` (docs-walkthrough DM6, DOC-9; DOCS-14), generated by `splicewire:beam:make:particle-op` and moved
 * into the package. Mounted at `GET beam/docs/search?q=&root=` inside `web` + `DocsReadAccess` + a throttle, never in a
 * tenant API group, so a guest reads public docs as a guest.
 *
 * ## Authorization (lead rulings 1-3, 08:04Z)
 *
 * `ability: false` is declared, not omitted, because authorization lives in two places that cover it completely:
 *
 * - `DocsReadAccess` decides whether this principal may read docs at all (404 otherwise), exactly as for a docs page;
 * - every candidate row passes the per-entry gate on EVERY request: `PublicEntryGate::chainForEntry()` (realm,
 *   ancestry, publish state, render access) AND `EntryAccessResolver::canList()` (the rule nav uses), so search never
 *   reveals a page nav hides.
 *
 * The root itself is resolved through the same gate for this principal and must be a `DocsLayout` root. The index is the
 * UNGATED, cached {@see DocsSearchIndex}; gating runs after the cache, so one principal's rows never reach another.
 * Bodies are the PUBLISHED ones only.
 *
 * ## Ranking
 *
 * A deterministic weighted sum, no index service: exact title > title prefix > title word > excerpt > heading > body
 * (capped), then shallower and earlier in nav. The root's readable `SpreadTemplate` surfaces (the API reference) are
 * always offered as `reference` rows (C-8). A query with no page hit falls back to the related product's docs (DOC-9).
 */
#[ParticleOp(
    resource: 'beam-docs',
    name: 'search',
    kind: OperationKind::Read,
    ability: false,
    affordance: false,
    input: DocsSearchInputData::class,
    output: DocsSearchResultsData::class,
    subject: NoSubject::class,
    method: HttpMethod::Get,
)]
class DocsSearchOp
{
    public const LIMIT = 10;

    public function __construct(
        private PublicEntryGate $gate,
        private EntryAccessResolver $access,
        private UrlResolver $urls,
        private DocsSearchIndex $index,
    ) {}

    public static function handle(mixed $model, Request $request, mixed $actor): DocsSearchResultsData
    {
        return app(self::class)->search(
            DocsSearchInputData::from($request->all()),
            $actor instanceof Authenticatable ? $actor : null,
        );
    }

    public function search(DocsSearchInputData $input, ?Authenticatable $actor): DocsSearchResultsData
    {
        $root = $this->root($input->root, $actor);
        $rows = $this->index->for($root);
        $realm = (string) ($root->realm ?? BeamUxEntry::REALM_SITE);
        $terms = $this->terms($input->q);

        $scored = [];
        foreach ($rows as $row) {
            $score = $this->score($row, mb_strtolower(trim($input->q)), $terms);
            if ($score > 0 && $row['template'] !== DocsChrome::SURFACE_TEMPLATE) {
                $scored[] = [$score, $row];
            }
        }
        usort($scored, fn (array $a, array $b) => [$b[0], $a[1]['depth'], $a[1]['order']] <=> [$a[0], $b[1]['depth'], $b[1]['order']]);

        $results = [];
        foreach ($scored as [, $row]) {
            if (count($results) >= self::LIMIT) {
                break;
            }
            $hit = $this->readable($row, $realm, $actor, 'page');
            if ($hit !== null) {
                $results[] = $hit;
            }
        }
        $pages = count($results);

        foreach ($rows as $row) {
            if ($row['depth'] === 1 && $row['template'] === DocsChrome::SURFACE_TEMPLATE) {
                $hit = $this->readable($row, $realm, $actor, 'reference');
                if ($hit !== null) {
                    $results[] = $hit;
                }
            }
        }

        return new DocsSearchResultsData(results: $results, fallback: $pages === 0 ? $this->fallback($input->q) : null);
    }

    /** The docs root the query is scoped to, resolved for this principal; anything else is the uniform 404. */
    private function root(string $root, ?Authenticatable $actor): BeamUxEntry
    {
        $path = trim((string) parse_url($root, PHP_URL_PATH), '/');
        $chain = $this->gate->chainFor($path, BeamUxEntry::REALM_SITE, $actor);
        $entry = $chain === null ? null : $chain[array_key_last($chain)];

        abort_if($entry === null || $entry->layout !== DocsChrome::LAYOUT, 404);

        return $entry;
    }

    /** The row as a result IF this principal may open AND list it (nav's rule); null otherwise. */
    private function readable(array $row, string $realm, ?Authenticatable $actor, string $kind): ?DocsSearchResultData
    {
        $entry = BeamUxEntry::query()->find($row['id']);
        $chain = $entry === null ? null : $this->gate->chainForEntry($entry, $realm, $actor);

        if ($chain === null || ! $this->access->canList($actor, $chain)) {
            return null;
        }

        return new DocsSearchResultData(
            title: $row['title'],
            href: $this->urls->resolveChain($chain),
            trail: $row['trail'],
            excerpt: $row['excerpt'],
            kind: $kind,
        );
    }

    /** @return list<string> */
    private function terms(string $q): array
    {
        return array_values(array_filter(preg_split('/[^\p{L}\p{N}]+/u', mb_strtolower($q)) ?: [], fn ($t) => mb_strlen($t) > 1));
    }

    /** @param  list<string>  $terms */
    private function score(array $row, string $q, array $terms): int
    {
        if ($terms === []) {
            return 0;
        }

        $title = mb_strtolower($row['title']);
        $words = preg_split('/[^\p{L}\p{N}]+/u', $title) ?: [];
        $score = 0;

        if ($title === $q) {
            $score += 100;
        } elseif (str_starts_with($title, $q)) {
            $score += 60;
        }

        $excerpt = mb_strtolower((string) $row['excerpt']);
        $headings = mb_strtolower($row['headings']);
        $text = mb_strtolower($row['text']);

        foreach ($terms as $term) {
            if (in_array($term, $words, true)) {
                $score += 40;
            }
            if ($excerpt !== '' && str_contains($excerpt, $term)) {
                $score += 20;
            }
            if ($headings !== '' && str_contains($headings, $term)) {
                $score += 10;
            }
            $score += min(5, substr_count($text, $term));
        }

        return $score;
    }

    /** Where a miss goes: the first related product that declares its docs, with the same query (DOC-9). */
    private function fallback(string $q): ?DocsSearchFallbackData
    {
        foreach ((array) config('beam.brands', []) as $key => $declared) {
            if (! is_array($declared) || ! is_string($declared['docs'] ?? null)) {
                continue;
            }
            $product = $this->product();
            if ($key === $product) {
                continue;
            }
            $name = BrandData::fromConfig($declared)->name;

            return new DocsSearchFallbackData(label: "Search {$name} docs", href: $declared['docs'].'?q='.rawurlencode($q));
        }

        return null;
    }

    private function product(): ?string
    {
        foreach ((array) config('beam.docs.sources', []) as $source) {
            if (is_string($source['product'] ?? null) && $source['product'] !== '') {
                return $source['product'];
            }
        }

        return null;
    }
}
