<?php

namespace Splicewire\Beam\Docs\Contracts;

use Spatie\TypeScriptTransformer\Transformers\AttributedClassTransformer;
use Spatie\TypeScriptTransformer\Transformers\EnumTransformer;
use Spatie\TypeScriptTransformer\TypeScriptTransformer;
use Spatie\TypeScriptTransformer\TypeScriptTransformerConfigFactory;
use Spatie\TypeScriptTransformer\Writers\FlatModuleWriter;
use Splicewire\Beam\Docs\Publishing\Data\PublicationData;
use Splicewire\Beam\Docs\Publishing\Data\PublishInputData;

/** The frontend's reproducible projection; rendering this map never writes files. */
class DocsFrontendContracts
{
    /** @return array<string, string> */
    public function files(): array
    {
        $root = dirname(__DIR__);
        $transformer = TypeScriptTransformer::create(
            TypeScriptTransformerConfigFactory::create()
                ->outputDirectory($root)
                ->transformDirectories($root.'/Publishing', $root.'/Data')
                ->transformer(new AttributedClassTransformer, new EnumTransformer)
                ->writer(new FlatModuleWriter('types.ts'))
                ->withoutManifest(),
        );
        [$types] = $transformer->resolveState();
        $files = [];
        foreach ($transformer->resolveFilesAction->execute($types) as $file) {
            $files[$file->path] = "// Generated by splicewire:beam:docs:export-contracts. Do not edit.\n".$file->contents;
        }

        $files['publish-input.schema.json'] = $this->json(PublishInputData::jsonSchema());
        $files['publication.schema.json'] = $this->json(PublicationData::jsonSchema());

        ksort($files);

        return $files;
    }

    private function json(array $schema): string
    {
        return json_encode($schema, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR)."\n";
    }
}
